apiVersion: v1
kind: ConfigMap
metadata:
  name: securebank-config
  namespace: securebank
data:
  DB_PORT: "5432"
  DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
  

---
apiVersion: v1
kind: Secret
metadata:
  name: securebank-secret
  namespace: securebank
type: Opaque
stringData:
  POSTGRES_USER: securebank
  POSTGRES_PASSWORD: c2VjdXJlYmFuaw==
  POSTGRES_DB: securebank
  POSTGRES_HOST: securebank-db

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
type: Opaque
stringData:
  slack_api_url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA0UjE3WkgwOTQvQjBCRjBSUDRXSFgvd3JDMWpFTm1BTWxtMFF6NGhkYjZaYXQ0