---
apiVersion: v1
kind: Namespace
metadata:
  name: securebank

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp3"
  hostPath:
    path: "/tmp/db-data"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: securebank-db
  namespace: securebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securebank-db
  template:
    metadata:
      labels:
        app: securebank-db
    spec:
      containers:
        - name: securebank-db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: securebank-secret
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "256Mi"
            limits:
              memory: "128Mi"
              cpu: "512Mi"

  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
      
             

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-be
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-be
  template:
    metadata:
      labels:
        app: securebank-be
    spec:
      containers:
        - name: securebank-be
          image: boluex/securebank-backend:16
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: securebank-config
                  key: DATABASE_URL

          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m" 
             


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-fe
  namespace: securebank
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-fe
  template:
    metadata:
      labels:
        app: securebank-fe
    spec:
      containers:
        - name: securebank-fe
          image: boluex/securebank-frontend:16
          ports:
            - containerPort: 80