---
apiVersion: v1
kind: Service
metadata:
  name: securebank-db
  namespace: securebank
spec:
  selector:
    app: securebank-db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: securebank-be
  namespace: securebank
  labels:
    app: securebank-be
spec:
  selector:
    app: securebank-be
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: securebank-fe
  namespace: securebank
spec:
  selector:
    app: securebank-fe
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: securebank-monitor
  namespace: securebank
spec:
  selector:
    matchLabels:
      app: securebank-be
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - securebank

